# Generated by Django 5.2.1 on 2025-10-26 21:00

import classifier.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TobaccoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=classifier.models.tobacco_image_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_tobacco', models.BooleanField(null=True)),
                ('blur_score', models.FloatField(blank=True, null=True)),
                ('grower_number', models.CharField(blank=True, max_length=50)),
                ('lot_number', models.CharField(blank=True, max_length=50)),
                ('bale_number', models.CharField(blank=True, max_length=50)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('price', models.FloatField()),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('tobacco_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='classifier.tobaccoimage')),
            ],
            options={
                'ordering': ['-classified_at'],
            },
        ),
    ]
