# Generated by Django 4.2.29 on 2026-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_tobaccoimage_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobaccoimage',
            name='group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
