name: Deploy Django

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Deploy application
        shell: bash -l {0}
        run: |
          cd /home/karoi-scale/Desktop/Tobacco_Classifier_Pricing

          git fetch origin
          git reset --hard origin/main

          conda activate env39

          pip install -r requirements.txt

          python manage.py migrate --noinput

          python manage.py collectstatic --noinput

          sudo systemctl restart tobacco

      ##- name: Verify service
        ##run: |
          ##systemctl is-active tobacco